### ISSUE TITLE
[Documentation]: Auto-generated API is broken

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#500] opened 2024-09-03 02:27 UTC
### What would you like changed or added to the documentation and why?

https://github.com/NeurodataWithoutBorders/nwbinspector/pull/486 moved all check functions and broke all check API docs here: https://nwbinspector.readthedocs.io/en/dev/api/checks.html#module-nwbinspector.checks.nwb_containers

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment] 2024-09-03 05:45
duplicate of https://github.com/NeurodataWithoutBorders/nwbinspector/issues/489, which we knew about at the time but I'm just going to get it done now

**Closed as completed** 2024-09-03 15:50 UTC
Labels: topic: docs
